services:
  superset:
    image: apache/superset:latest
    container_name: superset
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - superset_home:/app/superset_home
    environment:
      SUPERSET_ENV: production
    command: >
      gunicorn
      --bind 0.0.0.0:8088
      "superset.app:create_app()"

volumes:
  superset_home:
